<?php
session_start();
if (!isset($_SESSION['id']))
    header("Location: ../login.php");
require_once("ProductsDataSet.php");
require_once("dashboard-products.php");

?>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/images/favicon.jpg">

    <title>Fanatics Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/dashboard.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-dark sticky-top bg-white border-bottom border-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
        <img src="images/logo.png" width="180" height="35" </a>
    <a href="/Users.php?q=logout"
    <button class="btn btn-outline-dark" type="button">Log-Out</button>
    </a>

    <!--    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">-->
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-home.php">
                            <span data-feather="home"></span>
                            Dashboard Home <span class="sr-only"></span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file"></span>
                            Test
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="dashboard-products.php">
                            <span data-feather="shopping-cart"></span>
                            Products
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-signup.php">
                            <span data-feather="users"></span>
                            Add New Admin
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="bar-chart-2"></span>
                            Test
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Test
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Test Category</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Test
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Test
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Test
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Test
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>




<table class="table table-hover col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <thead>
    <tr>
        <th>Product ID</th>
        <th>Product Name</th>
        <th>Product Description</th>
        <th>Product Size</th>
        <th>Product Image</th>
        <th>Product Quantity</th>
        <th>Product Price</th>
        <th>Status</th>

    </tr>
    </thead>
    <tbody>



    <div class="col-md-9 ml-sm-auto col-lg-3 pt-3 px-4">
        <a href="#" data-toggle="modal" data-target="#add_product_modal" class="btn btn-primary btn-sm">Add Product</a>
    </div>

    <div class="col-md-9 ml-sm-auto col-lg-3 pt-3 px-4">
        <a href="#" data-toggle="modal" data-target="#edit_product_modal" class="btn btn-primary btn-sm">Delete Product</a>
    </div>

    <div class="col-md-9 ml-sm-auto col-lg-3 pt-3 px-4">
        <a href="#" data-toggle="modal" data-target="#status_product_modal" class="btn btn-primary btn-sm">Change Product Status</a>
    </div>

    <!-- Status Product Modal start -->
    <form action = "dashboard-products.php" method = "post">
        <div class="modal fade" id="status_product_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Change Product Product</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="edit-product-form" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Product ID</label>
                                        <input type="text" name="product_id" class="form-control" placeholder="Enter Product ID">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <select class="form-control status_list" name="product_status">
                                            <option value="">Select Status</option>
                                            <option value="Enabled">Enabled</option>
                                            <option value="Disabled">Disabled</option>
                                        </select>
                                    </div>
                                </div>
                                <input type="hidden" name="add_product" value="1">
                                <input type="submit" class="btn btn-primary" name="submit3" value="Submit">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- Status Product Modal end -->

    <!-- Edit Product Modal start -->
    <form action = "dashboard-products.php" method = "post">
        <div class="modal fade" id="edit_product_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete Product</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="edit-product-form" enctype="multipart/form-data">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label>Product ID</label>
                                        <input type="text" name="product_id" class="form-control" placeholder="Enter Product ID">
                                    </div>
                                </div>

                                <input type="hidden" name="add_product" value="1">
                                <input type="submit" class="btn btn-primary" name="submit2" value="Submit">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- Edit Product Modal end -->

    <!-- Add Product Modal start -->
    <form action = "dashboard-products.php" method = "post" enctype="multipart/form-data">
    <div class="modal fade" id="add_product_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add Product</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="add-product-form" enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Product Name</label>
                                    <input type="text" name="product_name" class="form-control" placeholder="Enter Product Name">
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Size</label>
                                    <select class="form-control size_list" name="product_size">
                                        <option value="">Select Size</option>
                                        <option value="XS">XS</option>
                                        <option value="S">S</option>
                                        <option value="M">M</option>
                                        <option value="L">L</option>
                                        <option value="XL">XL</option>
                                        <option value="2XL">XXL</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Product Description</label>
                                    <textarea class="form-control" name="product_description" placeholder="Enter Product Description"></textarea>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Product Quantity</label>
                                    <input type="number" name="product_quantity" class="form-control" placeholder="Enter Product Quantity">
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Product Price</label>
                                    <input type="number" step=".01" name="product_price" class="form-control" placeholder="Enter Product Price">
                                </div>
                            </div>
                            <div class="col-12">
<!--                                <div class="form-group">-->
<!--                                    <label>Product Image <small>(format: jpg, jpeg, png)</small></label>-->
<!--                                    <input type="file" name="product_image" class="form-control">-->
<!--                                </div>-->
                                <label>Product Image <small>(format: jpg, jpeg, png)</small></label>
                                <form method="POST" action="" enctype="multipart/form-data">
                                    <input type="file" name="product_image" value=""/>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Status</label>
                                    <select class="form-control status_list" name="product_status">
                                        <option value="">Select Status</option>
                                        <option value="Enabled">Enabled</option>
                                        <option value="Disabled">Disabled</option>
                                    </select>
                                </div>
                            </div>
                            <input type="hidden" name="add_product" value="1">
                            <input type="submit" class="btn btn-primary" name="submit" value="Submit">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </form>
    <!-- Add Product Modal end -->


<!--    --><?php


$conn = mysqli_connect('poseidon.salford.ac.uk','agd743','Gorvi402','agd743_hackcamp');


$sql = ("SELECT * FROM ProductInformation");
$result = $conn->query($sql);
    if ($result->num_rows > 0) {
        while ($row = $result->fetch_assoc()) {
            echo "<tr><td>" . $row["product_id"] . "</td><td>" . $row["product_name"] . "</td><td>" . $row["product_description"] . "</td><td>" . $row["product_size"] . "</td><td>" . "<img src=images/".$row['product_image'].' width=100px height="100px">' . "</td><td>" . $row["product_quantity"] . "</td><td>" . $row["product_price"] . "</td><td>" . $row["product_enabled"] . "</td>";
        }
    } else {
        echo "No Results";

}




if(isset($_POST['submit'])) {

    $filename = $_FILES["product_image"]["name"];
    $tempname = $_FILES["product_image"]["tmp_name"];
    $folder = "images/".$filename;
    $name = $_POST['product_name'];
    $price = $_POST['product_price'];
    //$file = $_POST['product_image'];
    $size = $_POST['product_size'];
    $quantity = $_POST['product_quantity'];
    $description = $_POST['product_description'];
    $status = $_POST['product_status'];
    $Str = str_replace("'", '', $description);


    $sql = "INSERT INTO ProductInformation (product_name,product_price,product_image,product_size,product_quantity,product_description,product_enabled) VALUES ('$name','$price','$filename','$size','$quantity','$Str','$status')";

    if (mysqli_query($conn, $sql)) {
        echo '<script>alert("Product has been successfully added - refresh page to view changes")</script>';
    } else {
        echo "Error: " . $sql . ":-" . mysqli_error($conn);
    }
    // Now let's move the uploaded image into the folder: image
    if (move_uploaded_file($tempname, $folder))  {
        $msg = "Image uploaded successfully";
    }else{
        $msg = "Failed to upload image";
    }
    mysqli_close($conn);




}


if(isset($_POST['submit2']))
{
    $id = $_POST['product_id'];
    $sql = "DELETE FROM ProductInformation WHERE product_id = '$id'";
    if (mysqli_query($conn, $sql)) {
        echo '<script>alert("Product has been successfully deleted - refresh page to view changes")</script>';
    } else {
        echo "Error: " . $sql . ":-" . mysqli_error($conn);
    }
    mysqli_close($conn);
}

if(isset($_POST['submit3']))
    {
        $id = $_POST['product_id'];
        $status = $_POST['product_status'];
        $sql = "UPDATE ProductInformation SET product_enabled = '$status' WHERE product_id = '$id'";
        if (mysqli_query($conn, $sql)) {
            echo '<script>alert("Product has been successfully edited - refresh page to view changes")</script>';
        } else {
            echo "Error: " . $sql . ":-" . mysqli_error($conn);
        }
        mysqli_close($conn);
    }


//include_once("database.php");
//       //output database fields in table using accessors
//
//            foreach ($view->productsDataSet as $productData) {
//            echo '<tr> <td>' . $productData->getProductID() .
//                '</td> <td>' . $productData->getProductName() .
//                '</td> <td>' . $productData->getProductDescription() .
//                '</td> <td>' . $productData->getProductSize() .
//                '</td> <td>' . '<img src="images/' . $productData->getProductPhotoName() . '"alt="No-Image"/>' .
//                '</td> <td>' . $productData->getProductQuantity() .
//                '</td> <td>' . $productData->getProductPrice() .
//
//                '</td> </td></tr>';
//        }
//             ?>
    </tbody>
    </table>
</form>



</body>
<!-- Add Product Modal end -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="js/vendor/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/product.js"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>