<?php

session_start();
if (!isset($_SESSION['id']))
    header("Location: ../login.php");
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/images/favicon.jpg">

    <title>Fanatics Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/dashboard.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-dark sticky-top bg-white border-bottom border-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
        <img src="images/logo.png" width="180" height="35" </a>
    <a href="/Users.php?q=logout"
    <button class="btn btn-outline-dark" type="button">Log-Out</button>
    </a>

    <!--    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">-->

</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Home</span>
                        <a class="d-flex align-items-center text-muted" href="#">
                            <span data-feather="chevron-down"></span>
                        </a>
                    </h6>
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-home.php">
                            <span data-feather="home"></span>
                            Dashboard Home <span class="sr-only"></span>
                        </a>
                    </li>
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Products</span>
                        <a class="d-flex align-items-center text-muted" href="#">
                            <span data-feather="chevron-down"></span>
                        </a>
                    </h6>
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-audit.php">
                            <span data-feather="file"></span>
                            Product Audit Log
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-products.php">
                            <span data-feather="shopping-cart"></span>
                            Products
                        </a>
                    </li>
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Users</span>
                        <a class="d-flex align-items-center text-muted" href="#">
                            <span data-feather="chevron-down"></span>
                        </a>
                    </h6>
                    <li class="nav-item">
                        <a class="nav-link active" href="dashboard-signup.php">
                            <span data-feather="users"></span>
                            Add New Admin
                        </a>
                    </li>
                </ul>
            </div>
        </nav>


        <?php
        require('session_helper.php');

        flash('register')
        ?>

        <head>
            <meta charset="utf-8">
            <title>Sign-Up</title>
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
        </head>
        <body>
        <div class="login">
            <h1>Sign-Up</h1>
            <form action="/Users.php" method="post">
                <input type = "hidden" name="type" value="register" >
                <label for="First Name">
                    <i class="fas fa-id-card"></i>
                </label>
                <input type="text" name="firstname" placeholder="Enter First Name" id="firstname" required>
                <label for="Last Name">
                    <i class="fas fa-id-card"></i>
                </label>
                <input type="text" name="lastname" placeholder="Enter Last Name" id="lastname" required>
                <label for="username">
                    <i class="fas fa-user"></i>
                </label>
                <input type="text" name="username" placeholder="Enter Username" id="username" required>
                <label for="password">
                    <i class="fas fa-lock"></i>
                </label>
                <input type="password" name="password" placeholder="Enter Password" id="password" required>
                <label for="password">
                    <i class="fas fa-lock"></i>
                </label>
                <input type="password" name="passwordrepeat" placeholder="Confirm Password" id="password" required>
                <input type="submit" value="Sign-Up">
            </form>
        </div>
        </body>



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="js/vendor/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>

</body>
</html>
