<?php
session_start();
if(!isset($_SESSION['id']))
    header("Location: ../login.php");
    ?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/images/favicon.jpg">

    <title>Fanatics Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/dashboard.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-dark sticky-top bg-white border-bottom border-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
    <img src="images/logo.png" width = "180" height="35" </a>
    <a href="/Users.php?q=logout"<button class="btn btn-outline-dark" type="button">Log-Out</button> </a>

<!--    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">-->

</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Home</span>
                        <a class="d-flex align-items-center text-muted" href="#">
                            <span data-feather="chevron-down"></span>
                        </a>
                    </h6>
                    <li class="nav-item">
                        <a class="nav-link active" href="dashboard-home.php">
                            <span data-feather="home"></span>
                            Dashboard Home <span class="sr-only"></span>
                        </a>
                    </li>
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Products</span>
                        <a class="d-flex align-items-center text-muted" href="#">
                            <span data-feather="chevron-down"></span>
                        </a>
                    </h6>
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-audit.php">
                            <span data-feather="file"></span>
                            Product Audit Log
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-products.php">
                            <span data-feather="shopping-cart"></span>
                            Products
                        </a>
                    </li>
                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Users</span>
                        <a class="d-flex align-items-center text-muted" href="#">
                            <span data-feather="chevron-down"></span>
                        </a>
                    </h6>
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-signup.php">
                            <span data-feather="users"></span>
                            Add New Admin
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
                <h1 class="h2">Welcome, <?php if(isset($_SESSION['id'])){
                        //display session username
                        echo explode(" ", $_SESSION['firstname'])[0];
                    }
                    ?></h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <div class="btn-group mr-2">
                    </div>
                </div>
            </div>


<!--            <canvas id="myChart" width="900" height="380"></canvas>-->
        <div class="col-auto">
            <h2 class="page-header" >Stock Levels</h2>
            <h4 class="page-header" >Ordered by 10 Lowest Stock</h4>
             <canvas  id="chartjs_bar"></canvas>
        </div>


            <h2>Table of Lowest Stock</h2>

            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Product ID</th>
                    <th>Product Name</th>
                    <th>Product Size</th>
                    <th>Image</th>
                    <th>Product Quantity</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>


                <?php


$conn = mysqli_connect('poseidon.salford.ac.uk','agd743','Gorvi402','agd743_hackcamp');
$sql = ("SELECT * FROM ProductInformation ORDER BY product_quantity ASC ");
$result = $conn->query($sql);
    if ($result->num_rows > 0) {
        while ($row = $result->fetch_assoc()) {
            echo "<tr><td>" . $row["product_id"] . "</td><td>" . $row["product_name"] . "</td><td>" . $row["product_size"] . "</td><td>" . "<img src=images/".$row['product_image'].' width=100px height="100px">' . "</td><td>" . $row["product_quantity"] . "</td><td>" . $row["product_enabled"] . "</td>";
        }
    } else {
        echo "No Results";

}
                $sql ="SELECT * FROM ProductInformation ORDER BY product_quantity ASC LIMIT 10";
                $result = mysqli_query($conn,$sql);
                $chart_data="";
                while ($row = mysqli_fetch_array($result)) {

                    $productname[]  = $row['product_id']  ;
                    $stock[] = $row['product_quantity'];
                }

  ?>
            </div>
        </main>
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="js/vendor/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.9.1.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>
<script type="text/javascript">
    var ctx = document.getElementById("chartjs_bar").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels:<?php echo json_encode($productname); ?>,
            datasets: [{
                backgroundColor: [
                    "#ff0000",
                    "#fe4400",
                    "#f86600",
                    "#ee8200",
                    "#df9b00",
                    "#cdb200",
                    "#b6c700",
                    "#99db00",
                    "#70ed00",
                    "#0bff00"

                ],

                data:<?php echo json_encode($stock); ?>,
            }]
        },
        options: {
            legend: {
                display: false,
                position: 'bottom',

                labels: {
                    fontColor: '#71748d',
                    fontFamily: 'Circular Std Book',
                    fontSize: 14,
                }
            },


        }
    });
</script>

</body>
</html>
