<?php
session_start();
if (!isset($_SESSION['id']))
    header("Location: ../login.php");
require_once("ProductsDataSet.php");
require_once("dashboard-products.php");

?>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/images/favicon.jpg">

    <title>Fanatics Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/dashboard.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-dark sticky-top bg-white border-bottom border-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">
        <img src="images/logo.png" width="180" height="35" </a>
    <a href="/Users.php?q=logout"
    <button class="btn btn-outline-dark" type="button">Log-Out</button>
    </a>

    <!--    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">-->
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-home.php">
                            <span data-feather="home"></span>
                            Dashboard Home <span class="sr-only"></span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file"></span>
                            Orders
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="dashboard-products.php">
                            <span data-feather="shopping-cart"></span>
                            Products
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="dashboard-signup.php">
                            <span data-feather="users"></span>
                            Add New Admin
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="bar-chart-2"></span>
                            Test
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="layers"></span>
                            Test
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Test Category</span>
                    <a class="d-flex align-items-center text-muted" href="#">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Test
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Test
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Test
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Test
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>
    <form method="post" action="/dashboard-products.php">
        <h3>Search for products</h3>
        <label>
            <input type="text" name="search" required/>
        </label>
        <input type="submit" value="Search"/>
    </form>

<table class="table table-hover col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <thead>
    <tr><th>Product ID</th><th>Product Name</th><th>Product Description</th><th>Product Size</th><th>Image</th><th>Product Quantity</th><th>Product Price</th></tr>

    </thead>
    <tbody>

    <?php
       //output database fields in table using accessors

            foreach ($view->productsDataSet as $productData) {
            echo '<tr> <td>' . $productData->getProductID() .
                '</td> <td>' . $productData->getProductName() .
                '</td> <td>' . $productData->getProductDescription() .
                '</td> <td>' . $productData->getProductSize() .
                '</td> <td>' . '<img src="images/' . $productData->getProductPhotoName() . '"alt="No-Image"/>' .
                '</td> <td>' . $productData->getProductQuantity() .
                '</td> <td>' . $productData->getProductPrice() .

                '</td> </td></tr>';
        }
             ?>
    </tbody>
    </table>
</form>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="js/vendor/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/product.js"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>